# Generated by Django 3.2.7 on 2021-09-19 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instruments_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_entry.employeename')),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_entry.paid')),
            ],
        ),
    ]
