# Generated by Django 3.2.7 on 2021-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_name', models.CharField(max_length=255)),
                ('travel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instruments_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
